### ISSUE TITLE
Settings screen cannot change timezone.

### ISSUE THREAD

**Issue by kgaddy** [kerberos-io/web#12]
It seems when you update the timezone, it just reverts back to the first item on the dropdown.

**Comment by cedricve** [comment]
The current timezone is selected by jquery on pageload, it could be that it takes some time to select the correct timezone.

If not probably the js files aren't loaded properly, you should refresh the page. Can you verify this?

**Comment by kgaddy** [comment]
I tried to change the timezone on the settings page. When I selected America/Chicago, then clicked "Update", it just reverted back to the first item Africa/Abidjan.
So you are saying it is set on document load for the settings page? 
I will take a look when I get home from work.

**Comment by kgaddy** [comment]
So it looks like the event is registered on document load. But it s needs to be set when the value is changed.

**Comment by stephanealpha** [comment]
Hi,
@cedricve, I do understand what @kgaddy means. 

When setting page is loaded, the timezone dropdown always shows the first selectable option.

I've changed timezone.blade.php and is works now. 

@kgaddy, try edit */home/kerberos-web/app/views/timezone.blade.php* and change:
_...
option[value='{{$value}}']").attr('selected','selected');
..._
by
_...
option[value='{{$value}}']").prop('selected',true);
..._

**Comment by cedricve** [comment]
Thank you Stephen, can you send a pull request?

**Comment by stephanealpha** [comment]
Hi Cedric,
As a noob on github, I don't really know what you mean :cry:

**Comment by cedricve** [comment]
Issue solved #17

**Comment by dannyzumwalt** [comment]
Having this issue on new install - v2.5 on RPi B. 

---
New install on RPi B. The camera configuration web interface will not let me change timezone from default "Europe/Brussels +02:00". I am trying to set it to America/Denver -06:00 and have also tried other cities, but after clicking Update, the timezone always resets to Brussels. All my timestamps show the wrong timezone because of this. Tried rebooting. I see this issue was brought up in the past with a fix to timezone.blade.php, and I confirmed my timezone.blade.php file has the updated code, but still the issue persists.
