### ISSUE TITLE
Motion sensitivity

### ISSUE THREAD

**Issue by sirkro** [kerberos-io/web#85]
I got an Hikvision DS-2CD2042WD-I

I decreased the sensitivity in "web" but I still get motion on:
Insects, birds, rain and reflections on a parked car window.

Running web and machinery on docker.

Is this a bug with web not setting settings as it should, or is the sensitivity on kerberos to sensitiv?

**Comment by cedricve** [comment]
Hey Sirkro,

Hmm well ignoring insects and or light reflections is a hard one. Although you shouldn't place a camera behind a window.

What you can do is minimize the region of interest by selecting a hull, and decrease the sensitivity a bit.

Cédric

**Comment by sirkro** [comment]
The sensitivity is all the way down, and it triggers on insects, hedgehogs, birds, and reflection on car windows. Camera is not behind a window.

**Comment by cedricve** [comment]
Ok, Kerberos.io will always take snapshots if some significant portion of the viewport changed. With the basic view you can control one property (the intensity change). 

What you can do to get more control is activate the advanced settings, and open the algorithm property.

![screen shot 2017-07-04 at 16 16 35](https://user-images.githubusercontent.com/1546779/27833704-3281f768-60d4-11e7-8b2e-4733580d012b.png)
![screen shot 2017-07-04 at 16 16 23](https://user-images.githubusercontent.com/1546779/27833705-3284517a-60d4-11e7-9813-e5bc69282ed0.png)

You should increase the erode property (https://doc.kerberos.io/2.0/machinery/algorithms/differential_images). By increasing it you will remove smaller objects from the viewport. The reason why we didn't added it to the basic view is because most of the basic user do not care about this.
